//
// AssetsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class AssetsAPI: APIBase {
    /**
     * enum for parameter datasource
     */
    public enum Datasource_getCharactersCharacterIdAssets: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     Get character assets
     
     - parameter characterId: (path) Character id of the target character 
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getCharactersCharacterIdAssets(characterId characterId: Int32, datasource: Datasource_getCharactersCharacterIdAssets? = nil, completion: ((data: [GetCharactersCharacterIdAssets200Ok]?, error: ErrorType?) -> Void)) {
        getCharactersCharacterIdAssetsWithRequestBuilder(characterId: characterId, datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get character assets
     - GET /characters/{characterId}/assets/
     - Return a list of the characters assets  ---  Alternate route: `/v1/characters/{character_id}/assets/`  Alternate route: `/legacy/characters/{character_id}/assets/`  Alternate route: `/dev/characters/{character_id}/assets/`   ---  This route is cached for up to 3600 seconds
     - OAuth:
       - type: oauth2
       - name: evesso
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example=[ {
  "is_singleton" : true,
  "item_id" : 1000000016835,
  "location_flag" : "Hangar",
  "location_id" : 60002959,
  "location_type" : "station",
  "type_id" : 3516
} ]}]
     
     - parameter characterId: (path) Character id of the target character 
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<[GetCharactersCharacterIdAssets200Ok]> 
     */
    public class func getCharactersCharacterIdAssetsWithRequestBuilder(characterId characterId: Int32, datasource: Datasource_getCharactersCharacterIdAssets? = nil) -> RequestBuilder<[GetCharactersCharacterIdAssets200Ok]> {
        var path = "/characters/{characterId}/assets/"
        path = path.stringByReplacingOccurrencesOfString("{characterId}", withString: "\(characterId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[GetCharactersCharacterIdAssets200Ok]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
