//
// ClonesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ClonesAPI: APIBase {
    /**
     * enum for parameter datasource
     */
    public enum Datasource_getCharactersCharacterIdClones: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     Get clones
     
     - parameter characterId: (path) An EVE character ID 
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getCharactersCharacterIdClones(characterId characterId: Int32, datasource: Datasource_getCharactersCharacterIdClones? = nil, completion: ((data: GetCharactersCharacterIdClonesOk?, error: ErrorType?) -> Void)) {
        getCharactersCharacterIdClonesWithRequestBuilder(characterId: characterId, datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get clones
     - GET /characters/{characterId}/clones/
     - A list of the character's clones  ---  Alternate route: `/v2/characters/{character_id}/clones/`  Alternate route: `/dev/characters/{character_id}/clones/`   ---  This route is cached for up to 120 seconds
     - OAuth:
       - type: oauth2
       - name: evesso
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example={
  "home_location" : {
    "location_id" : 1021348135816,
    "location_type" : "structure"
  },
  "jump_clones" : [ {
    "implants" : [ 22118 ],
    "location_id" : 60003463,
    "location_type" : "station"
  }, {
    "implants" : [ ],
    "location_id" : 1021348135816,
    "location_type" : "structure"
  } ]
}}]
     
     - parameter characterId: (path) An EVE character ID 
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<GetCharactersCharacterIdClonesOk> 
     */
    public class func getCharactersCharacterIdClonesWithRequestBuilder(characterId characterId: Int32, datasource: Datasource_getCharactersCharacterIdClones? = nil) -> RequestBuilder<GetCharactersCharacterIdClonesOk> {
        var path = "/characters/{characterId}/clones/"
        path = path.stringByReplacingOccurrencesOfString("{characterId}", withString: "\(characterId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<GetCharactersCharacterIdClonesOk>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
