//
// IncursionsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class IncursionsAPI: APIBase {
    /**
     * enum for parameter datasource
     */
    public enum Datasource_getIncursions: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     List incursions
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getIncursions(datasource datasource: Datasource_getIncursions? = nil, completion: ((data: [GetIncursions200Ok]?, error: ErrorType?) -> Void)) {
        getIncursionsWithRequestBuilder(datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List incursions
     - GET /incursions/
     - Return a list of current incursions  ---  Alternate route: `/v1/incursions/`  Alternate route: `/legacy/incursions/`  Alternate route: `/dev/incursions/`   ---  This route is cached for up to 300 seconds
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example=[ {
  "constellation_id" : 20000607,
  "faction_id" : 500019,
  "has_boss" : true,
  "infested_solar_systems" : [ 30004148, 30004149, 30004150, 30004151, 30004152, 30004153, 30004154 ],
  "influence" : 1.0,
  "staging_solar_system_id" : 30004154,
  "state" : "mobilizing",
  "type" : "Incursion"
} ]}]
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<[GetIncursions200Ok]> 
     */
    public class func getIncursionsWithRequestBuilder(datasource datasource: Datasource_getIncursions? = nil) -> RequestBuilder<[GetIncursions200Ok]> {
        let path = "/incursions/"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[GetIncursions200Ok]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
