//
// IndustryAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class IndustryAPI: APIBase {
    /**
     * enum for parameter datasource
     */
    public enum Datasource_getIndustryFacilities: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     List industry facilities
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getIndustryFacilities(datasource datasource: Datasource_getIndustryFacilities? = nil, completion: ((data: [GetIndustryFacilities200Ok]?, error: ErrorType?) -> Void)) {
        getIndustryFacilitiesWithRequestBuilder(datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List industry facilities
     - GET /industry/facilities/
     - Return a list of industry facilities  ---  Alternate route: `/v1/industry/facilities/`  Alternate route: `/legacy/industry/facilities/`  Alternate route: `/dev/industry/facilities/`   ---  This route is cached for up to 3600 seconds
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example=[ {
  "facility_id" : 60012544,
  "owner_id" : 1000126,
  "region_id" : 10000001,
  "solar_system_id" : 30000032,
  "tax" : 0.1,
  "type_id" : 2502
} ]}]
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<[GetIndustryFacilities200Ok]> 
     */
    public class func getIndustryFacilitiesWithRequestBuilder(datasource datasource: Datasource_getIndustryFacilities? = nil) -> RequestBuilder<[GetIndustryFacilities200Ok]> {
        let path = "/industry/facilities/"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[GetIndustryFacilities200Ok]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     * enum for parameter datasource
     */
    public enum Datasource_getIndustrySystems: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     List solar system cost indices
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getIndustrySystems(datasource datasource: Datasource_getIndustrySystems? = nil, completion: ((data: [GetIndustrySystems200Ok]?, error: ErrorType?) -> Void)) {
        getIndustrySystemsWithRequestBuilder(datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List solar system cost indices
     - GET /industry/systems/
     - Return cost indices for solar systems  ---  Alternate route: `/v1/industry/systems/`  Alternate route: `/legacy/industry/systems/`  Alternate route: `/dev/industry/systems/`   ---  This route is cached for up to 3600 seconds
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example=[ {
  "cost_indices" : [ {
    "activity" : "invention",
    "cost_index" : 0.00480411064973412
  } ],
  "solar_system_id" : 30011392
} ]}]
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<[GetIndustrySystems200Ok]> 
     */
    public class func getIndustrySystemsWithRequestBuilder(datasource datasource: Datasource_getIndustrySystems? = nil) -> RequestBuilder<[GetIndustrySystems200Ok]> {
        let path = "/industry/systems/"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[GetIndustrySystems200Ok]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
