//
// InsuranceAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class InsuranceAPI: APIBase {
    /**
     * enum for parameter datasource
     */
    public enum Datasource_getInsurancePrices: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     List insurance levels
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getInsurancePrices(datasource datasource: Datasource_getInsurancePrices? = nil, completion: ((data: [GetInsurancePrices200Ok]?, error: ErrorType?) -> Void)) {
        getInsurancePricesWithRequestBuilder(datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List insurance levels
     - GET /insurance/prices/
     - Return available insurance levels for all ship types  ---  Alternate route: `/v1/insurance/prices/`  Alternate route: `/legacy/insurance/prices/`  Alternate route: `/dev/insurance/prices/`   ---  This route is cached for up to 3600 seconds
     - responseHeaders: [Cache-Control(String), Content-Language(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Content-Language(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Content-Language(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Content-Language(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example=[ {
  "levels" : [ {
    "cost" : 10.0,
    "name" : "Basic",
    "payout" : 20.0
  } ],
  "type_id" : 1
} ]}]
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<[GetInsurancePrices200Ok]> 
     */
    public class func getInsurancePricesWithRequestBuilder(datasource datasource: Datasource_getInsurancePrices? = nil) -> RequestBuilder<[GetInsurancePrices200Ok]> {
        let path = "/insurance/prices/"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[GetInsurancePrices200Ok]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
