//
// SovereigntyAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class SovereigntyAPI: APIBase {
    /**
     * enum for parameter datasource
     */
    public enum Datasource_getSovereigntyCampaigns: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     List sovereignty campaigns
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSovereigntyCampaigns(datasource datasource: Datasource_getSovereigntyCampaigns? = nil, completion: ((data: [GetSovereigntyCampaigns200Ok]?, error: ErrorType?) -> Void)) {
        getSovereigntyCampaignsWithRequestBuilder(datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List sovereignty campaigns
     - GET /sovereignty/campaigns/
     - Shows sovereignty data for campaigns.  ---  Alternate route: `/v1/sovereignty/campaigns/`  Alternate route: `/legacy/sovereignty/campaigns/`  Alternate route: `/dev/sovereignty/campaigns/`   ---  This route is cached for up to 5 seconds
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example=[ {
  "attackers_score" : 0.4,
  "campaign_id" : 32833,
  "constellation_id" : 20000125,
  "defender_id" : 1695357456,
  "defender_score" : 0.6,
  "event_type" : "station_defense",
  "solar_system_id" : 30000856,
  "start_time" : "2016-10-29T14:34:40Z",
  "structure_id" : 61001096
} ]}]
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<[GetSovereigntyCampaigns200Ok]> 
     */
    public class func getSovereigntyCampaignsWithRequestBuilder(datasource datasource: Datasource_getSovereigntyCampaigns? = nil) -> RequestBuilder<[GetSovereigntyCampaigns200Ok]> {
        let path = "/sovereignty/campaigns/"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[GetSovereigntyCampaigns200Ok]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     * enum for parameter datasource
     */
    public enum Datasource_getSovereigntyStructures: String { 
        case Tranquility = "tranquility"
        case Singularity = "singularity"
    }

    /**
     List sovereignty structures
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSovereigntyStructures(datasource datasource: Datasource_getSovereigntyStructures? = nil, completion: ((data: [GetSovereigntyStructures200Ok]?, error: ErrorType?) -> Void)) {
        getSovereigntyStructuresWithRequestBuilder(datasource: datasource).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     List sovereignty structures
     - GET /sovereignty/structures/
     - Shows sovereignty data for structures.  ---  Alternate route: `/v1/sovereignty/structures/`  Alternate route: `/legacy/sovereignty/structures/`  Alternate route: `/dev/sovereignty/structures/`   ---  This route is cached for up to 120 seconds
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - responseHeaders: [Cache-Control(String), Expires(String), Last-Modified(String)]
     - examples: [{contentType=application/json, example=[ {
  "alliance_id" : 498125261,
  "solar_system_id" : 30000570,
  "structure_id" : 1018253388776,
  "structure_type_id" : 32226,
  "vulnerability_occupancy_level" : 2,
  "vulnerable_end_time" : "2016-10-29T05:30:00Z",
  "vulnerable_start_time" : "2016-10-28T20:30:00Z"
} ]}]
     
     - parameter datasource: (query) The server name you would like data from (optional, default to tranquility)

     - returns: RequestBuilder<[GetSovereigntyStructures200Ok]> 
     */
    public class func getSovereigntyStructuresWithRequestBuilder(datasource datasource: Datasource_getSovereigntyStructures? = nil) -> RequestBuilder<[GetSovereigntyStructures200Ok]> {
        let path = "/sovereignty/structures/"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "datasource": datasource?.rawValue
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[GetSovereigntyStructures200Ok]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
