//
// CharacterscharacterIdbookmarksTarget.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** target object */
public class CharacterscharacterIdbookmarksTarget: JSONEncodable {
    public var coordinates: CharacterscharacterIdbookmarksTargetCoordinates?
    public var item: CharacterscharacterIdbookmarksTargetItem?
    /** location_id integer */
    public var locationId: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["coordinates"] = self.coordinates?.encodeToJSON()
        nillableDictionary["item"] = self.item?.encodeToJSON()
        nillableDictionary["location_id"] = self.locationId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
