//
// CharacterscharacterIdmailRecipients1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** recipient object */
public class CharacterscharacterIdmailRecipients1: JSONEncodable {
    public enum RecipientType: String { 
        case Alliance = "alliance"
        case Character = "character"
        case Corporation = "corporation"
        case MailingList = "mailing_list"
    }
    /** recipient_id integer */
    public var recipientId: Int32?
    /** recipient_type string */
    public var recipientType: RecipientType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["recipient_id"] = self.recipientId?.encodeToJSON()
        nillableDictionary["recipient_type"] = self.recipientType?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
