//
// CharacterscharacterIdbookmarksTargetCoordinates.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** coordinates object */
public class CharacterscharacterIdbookmarksTargetCoordinates: JSONEncodable {
    /** x number */
    public var x: Double?
    /** y number */
    public var y: Double?
    /** z number */
    public var z: Double?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["x"] = self.x
        nillableDictionary["y"] = self.y
        nillableDictionary["z"] = self.z
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
