//
// CorporationscorporationIdalliancehistoryAlliance.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** alliance object */
public class CorporationscorporationIdalliancehistoryAlliance: JSONEncodable {
    /** alliance_id integer */
    public var allianceId: Int32?
    /** True if the alliance has been deleted */
    public var isDeleted: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["alliance_id"] = self.allianceId?.encodeToJSON()
        nillableDictionary["is_deleted"] = self.isDeleted
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
