//
// GetAlliancesAllianceIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetAlliancesAllianceIdOk: JSONEncodable {
    /** the full name of the alliance */
    public var allianceName: String?
    /** date_founded string */
    public var dateFounded: NSDate?
    /** the executor corporation ID, if this alliance is not closed */
    public var executorCorp: Int32?
    /** the short name of the alliance */
    public var ticker: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["alliance_name"] = self.allianceName
        nillableDictionary["date_founded"] = self.dateFounded?.encodeToJSON()
        nillableDictionary["executor_corp"] = self.executorCorp?.encodeToJSON()
        nillableDictionary["ticker"] = self.ticker
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
