//
// GetCharactersCharacterIdPlanetsPlanetIdOkFactoryDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** factory_details object */
public class GetCharactersCharacterIdPlanetsPlanetIdOkFactoryDetails: JSONEncodable {
    /** schematic_id integer */
    public var schematicId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["schematic_id"] = self.schematicId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
