//
// GetCharactersNames200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersNames200Ok: JSONEncodable {
    /** character_id integer */
    public var characterId: Int64?
    /** character_name string */
    public var characterName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["character_id"] = self.characterId?.encodeToJSON()
        nillableDictionary["character_name"] = self.characterName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
