//
// GetCharactersCharacterIdMailLabelsOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdMailLabelsOk: JSONEncodable {
    /** labels array */
    public var labels: [GetCharactersCharacterIdMailLabelsOkLabels]?
    /** total_unread_count integer */
    public var totalUnreadCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["labels"] = self.labels?.encodeToJSON()
        nillableDictionary["total_unread_count"] = self.totalUnreadCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
