//
// GetCharactersCharacterIdWallets200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdWallets200Ok: JSONEncodable {
    /** Wallet&#39;s balance in ISK hundredths. */
    public var balance: Int64?
    /** wallet_id integer */
    public var walletId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["balance"] = self.balance?.encodeToJSON()
        nillableDictionary["wallet_id"] = self.walletId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
