//
// GetCharactersCharacterIdSkillqueue200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdSkillqueue200Ok: JSONEncodable {
    /** finish_date string */
    public var finishDate: NSDate?
    /** finished_level integer */
    public var finishedLevel: Int32?
    /** level_end_sp integer */
    public var levelEndSp: Int32?
    /** Amount of SP that was in the skill when it started training it&#39;s current level. Used to calculate % of current level complete. */
    public var levelStartSp: Int32?
    /** queue_position integer */
    public var queuePosition: Int32?
    /** skill_id integer */
    public var skillId: Int32?
    /** start_date string */
    public var startDate: NSDate?
    /** training_start_sp integer */
    public var trainingStartSp: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["finish_date"] = self.finishDate?.encodeToJSON()
        nillableDictionary["finished_level"] = self.finishedLevel?.encodeToJSON()
        nillableDictionary["level_end_sp"] = self.levelEndSp?.encodeToJSON()
        nillableDictionary["level_start_sp"] = self.levelStartSp?.encodeToJSON()
        nillableDictionary["queue_position"] = self.queuePosition?.encodeToJSON()
        nillableDictionary["skill_id"] = self.skillId?.encodeToJSON()
        nillableDictionary["start_date"] = self.startDate?.encodeToJSON()
        nillableDictionary["training_start_sp"] = self.trainingStartSp?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
