//
// GetCharactersCharacterIdPlanetsPlanetIdOkRoutes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** route object */
public class GetCharactersCharacterIdPlanetsPlanetIdOkRoutes: JSONEncodable {
    /** content_type_id integer */
    public var contentTypeId: Int32?
    /** destination_pin_id integer */
    public var destinationPinId: Int64?
    /** quantity integer */
    public var quantity: Int64?
    /** route_id integer */
    public var routeId: Int64?
    /** source_pin_id integer */
    public var sourcePinId: Int64?
    /** waypoints array */
    public var waypoints: [GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["content_type_id"] = self.contentTypeId?.encodeToJSON()
        nillableDictionary["destination_pin_id"] = self.destinationPinId?.encodeToJSON()
        nillableDictionary["quantity"] = self.quantity?.encodeToJSON()
        nillableDictionary["route_id"] = self.routeId?.encodeToJSON()
        nillableDictionary["source_pin_id"] = self.sourcePinId?.encodeToJSON()
        nillableDictionary["waypoints"] = self.waypoints?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
