//
// GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** waypoint object */
public class GetCharactersCharacterIdPlanetsPlanetIdOkWaypoints: JSONEncodable {
    /** order integer */
    public var order: Int32?
    /** pin_id integer */
    public var pinId: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["order"] = self.order?.encodeToJSON()
        nillableDictionary["pin_id"] = self.pinId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
