//
// GetCharactersCharacterIdBookmarks200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdBookmarks200Ok: JSONEncodable {
    /** bookmark_id integer */
    public var bookmarkId: Int64?
    /** create_date string */
    public var createDate: NSDate?
    /** creator_id integer */
    public var creatorId: Int32?
    /** folder_id integer */
    public var folderId: Int32?
    /** memo string */
    public var memo: String?
    /** note string */
    public var note: String?
    /** owner_id integer */
    public var ownerId: Int32?
    public var target: CharacterscharacterIdbookmarksTarget?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["bookmark_id"] = self.bookmarkId?.encodeToJSON()
        nillableDictionary["create_date"] = self.createDate?.encodeToJSON()
        nillableDictionary["creator_id"] = self.creatorId?.encodeToJSON()
        nillableDictionary["folder_id"] = self.folderId?.encodeToJSON()
        nillableDictionary["memo"] = self.memo
        nillableDictionary["note"] = self.note
        nillableDictionary["owner_id"] = self.ownerId?.encodeToJSON()
        nillableDictionary["target"] = self.target?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
