//
// GetCharactersCharacterIdPlanets200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdPlanets200Ok: JSONEncodable {
    public enum PlanetType: String { 
        case Temperate = "temperate"
        case Barren = "barren"
        case Oceanic = "oceanic"
        case Ice = "ice"
        case Gas = "gas"
        case Lava = "lava"
        case Storm = "storm"
        case Plasma = "plasma"
    }
    /** last_update string */
    public var lastUpdate: NSDate?
    /** num_pins integer */
    public var numPins: Int32?
    /** owner_id integer */
    public var ownerId: Int32?
    /** planet_id integer */
    public var planetId: Int32?
    /** planet_type string */
    public var planetType: PlanetType?
    /** solar_system_id integer */
    public var solarSystemId: Int32?
    /** upgrade_level integer */
    public var upgradeLevel: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["last_update"] = self.lastUpdate?.encodeToJSON()
        nillableDictionary["num_pins"] = self.numPins?.encodeToJSON()
        nillableDictionary["owner_id"] = self.ownerId?.encodeToJSON()
        nillableDictionary["planet_id"] = self.planetId?.encodeToJSON()
        nillableDictionary["planet_type"] = self.planetType?.rawValue
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["upgrade_level"] = self.upgradeLevel?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
