//
// GetCharactersCharacterIdPortraitOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdPortraitOk: JSONEncodable {
    /** px128x128 string */
    public var px128x128: String?
    /** px256x256 string */
    public var px256x256: String?
    /** px512x512 string */
    public var px512x512: String?
    /** px64x64 string */
    public var px64x64: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["px128x128"] = self.px128x128
        nillableDictionary["px256x256"] = self.px256x256
        nillableDictionary["px512x512"] = self.px512x512
        nillableDictionary["px64x64"] = self.px64x64
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
