//
// GetCharactersCharacterIdMailMailIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdMailMailIdOk: JSONEncodable {
    /** Mail&#39;s body */
    public var body: String?
    /** From whom the mail was sent */
    public var from: Int32?
    /** Labels attached to the mail */
    public var labels: [Int64]?
    /** Whether the mail is flagged as read */
    public var read: Bool?
    /** Recipients of the mail */
    public var recipients: [GetCharactersCharacterIdMailMailIdOkRecipients]?
    /** Mail subject */
    public var subject: String?
    /** When the mail was sent */
    public var timestamp: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["body"] = self.body
        nillableDictionary["from"] = self.from?.encodeToJSON()
        nillableDictionary["labels"] = self.labels?.encodeToJSON()
        nillableDictionary["read"] = self.read
        nillableDictionary["recipients"] = self.recipients?.encodeToJSON()
        nillableDictionary["subject"] = self.subject
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
