//
// GetCharactersCharacterIdSkillsOkSkills.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** skill object */
public class GetCharactersCharacterIdSkillsOkSkills: JSONEncodable {
    /** current_skill_level integer */
    public var currentSkillLevel: Int32?
    /** skill_id integer */
    public var skillId: Int32?
    /** skillpoints_in_skill integer */
    public var skillpointsInSkill: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["current_skill_level"] = self.currentSkillLevel?.encodeToJSON()
        nillableDictionary["skill_id"] = self.skillId?.encodeToJSON()
        nillableDictionary["skillpoints_in_skill"] = self.skillpointsInSkill?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
