//
// GetCharactersCharacterIdPlanetsPlanetIdOkContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** content object */
public class GetCharactersCharacterIdPlanetsPlanetIdOkContent: JSONEncodable {
    /** content integer */
    public var content: Int32?
    /** content_quantity integer */
    public var contentQuantity: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["content"] = self.content?.encodeToJSON()
        nillableDictionary["content_quantity"] = self.contentQuantity?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
