//
// GetCharactersCharacterIdShipOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdShipOk: JSONEncodable {
    /** Item id&#39;s are unique to a ship and persist until it is repackaged. This value can be used to track repeated uses of a ship, or detect when a pilot changes into a different instance of the same ship type. */
    public var shipItemId: Int64?
    /** ship_name string */
    public var shipName: String?
    /** ship_type_id integer */
    public var shipTypeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ship_item_id"] = self.shipItemId?.encodeToJSON()
        nillableDictionary["ship_name"] = self.shipName
        nillableDictionary["ship_type_id"] = self.shipTypeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
