//
// GetCharactersCharacterIdClonesOkJumpClones.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** jump_clone object */
public class GetCharactersCharacterIdClonesOkJumpClones: JSONEncodable {
    public enum LocationType: String { 
        case Station = "station"
        case Structure = "structure"
    }
    /** implants array */
    public var implants: [Int32]?
    /** location_id integer */
    public var locationId: Int64?
    /** location_type string */
    public var locationType: LocationType?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["implants"] = self.implants?.encodeToJSON()
        nillableDictionary["location_id"] = self.locationId?.encodeToJSON()
        nillableDictionary["location_type"] = self.locationType?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
