//
// GetCharactersCharacterIdPlanetsPlanetIdOkExtractorDetailsHeads.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** head object */
public class GetCharactersCharacterIdPlanetsPlanetIdOkExtractorDetailsHeads: JSONEncodable {
    /** head_id integer */
    public var headId: Int32?
    /** latitude number */
    public var latitude: Float?
    /** longitude number */
    public var longitude: Float?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["head_id"] = self.headId?.encodeToJSON()
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
