//
// GetCharactersCharacterIdMail200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdMail200Ok: JSONEncodable {
    /** From whom the mail was sent */
    public var from: Int32?
    /** is_read boolean */
    public var isRead: Bool?
    /** labels array */
    public var labels: [Int64]?
    /** mail_id integer */
    public var mailId: Int64?
    /** Recipients of the mail */
    public var recipients: [CharacterscharacterIdmailRecipients]?
    /** Mail subject */
    public var subject: String?
    /** When the mail was sent */
    public var timestamp: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["from"] = self.from?.encodeToJSON()
        nillableDictionary["is_read"] = self.isRead
        nillableDictionary["labels"] = self.labels?.encodeToJSON()
        nillableDictionary["mail_id"] = self.mailId?.encodeToJSON()
        nillableDictionary["recipients"] = self.recipients?.encodeToJSON()
        nillableDictionary["subject"] = self.subject
        nillableDictionary["timestamp"] = self.timestamp?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
