//
// GetCharactersCharacterIdBookmarksFolders200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdBookmarksFolders200Ok: JSONEncodable {
    /** folder_id integer */
    public var folderId: Int32?
    /** name string */
    public var name: String?
    /** owner_id integer */
    public var ownerId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["folder_id"] = self.folderId?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["owner_id"] = self.ownerId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
