//
// GetCharactersCharacterIdCorporationhistory200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdCorporationhistory200Ok: JSONEncodable {
    /** corporation_id integer */
    public var corporationId: Int32?
    /** True if the corporation has been deleted */
    public var isDeleted: Bool?
    /** An incrementing ID that can be used to canonically establish order of records in cases where dates may be ambiguous */
    public var recordId: Int32?
    /** start_date string */
    public var startDate: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["corporation_id"] = self.corporationId?.encodeToJSON()
        nillableDictionary["is_deleted"] = self.isDeleted
        nillableDictionary["record_id"] = self.recordId?.encodeToJSON()
        nillableDictionary["start_date"] = self.startDate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
