//
// GetCharactersCharacterIdLocationOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdLocationOk: JSONEncodable {
    /** solar_system_id integer */
    public var solarSystemId: Int32?
    /** station_id integer */
    public var stationId: Int32?
    /** structure_id integer */
    public var structureId: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["station_id"] = self.stationId?.encodeToJSON()
        nillableDictionary["structure_id"] = self.structureId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
