//
// GetCharactersCharacterIdKillmailsRecent200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdKillmailsRecent200Ok: JSONEncodable {
    /** A hash of this killmail */
    public var killmailHash: String?
    /** ID of this killmail */
    public var killmailId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["killmail_hash"] = self.killmailHash
        nillableDictionary["killmail_id"] = self.killmailId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
