//
// GetCharactersCharacterIdMailLabelsOkLabels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** label object */
public class GetCharactersCharacterIdMailLabelsOkLabels: JSONEncodable {
    public enum Color: String { 
        case #ffffff = "#ffffff"
        case #ffff01 = "#ffff01"
        case #ff6600 = "#ff6600"
        case #fe0000 = "#fe0000"
        case #9a0000 = "#9a0000"
        case #660066 = "#660066"
        case #0000fe = "#0000fe"
        case #0099ff = "#0099ff"
        case #01ffff = "#01ffff"
        case #00ff33 = "#00ff33"
        case #349800 = "#349800"
        case #006634 = "#006634"
        case #666666 = "#666666"
        case #999999 = "#999999"
        case #e6e6e6 = "#e6e6e6"
        case #ffffcd = "#ffffcd"
        case #99ffff = "#99ffff"
        case #ccff9a = "#ccff9a"
    }
    /** color string */
    public var color: Color?
    /** label_id integer */
    public var labelId: Int32?
    /** name string */
    public var name: String?
    /** unread_count integer */
    public var unreadCount: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["color"] = self.color?.rawValue
        nillableDictionary["label_id"] = self.labelId?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["unread_count"] = self.unreadCount?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
