//
// GetCorporationsNames200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCorporationsNames200Ok: JSONEncodable {
    /** corporation_id integer */
    public var corporationId: Int32?
    /** corporation_name string */
    public var corporationName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["corporation_id"] = self.corporationId?.encodeToJSON()
        nillableDictionary["corporation_name"] = self.corporationName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
