//
// GetCharactersCharacterIdPlanetsPlanetIdOkLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** link object */
public class GetCharactersCharacterIdPlanetsPlanetIdOkLinks: JSONEncodable {
    /** destination_pin_id integer */
    public var destinationPinId: Int64?
    /** link_level integer */
    public var linkLevel: Int32?
    /** source_pin_id integer */
    public var sourcePinId: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["destination_pin_id"] = self.destinationPinId?.encodeToJSON()
        nillableDictionary["link_level"] = self.linkLevel?.encodeToJSON()
        nillableDictionary["source_pin_id"] = self.sourcePinId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
