//
// GetCharactersCharacterIdCalendarEventIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Full details of a specific event */
public class GetCharactersCharacterIdCalendarEventIdOk: JSONEncodable {
    public enum OwnerType: String { 
        case EveServer = "eve_server"
        case Corporation = "corporation"
        case Faction = "faction"
        case Character = "character"
        case Alliance = "alliance"
    }
    /** date string */
    public var date: NSDate?
    /** Length in minutes */
    public var duration: Int64?
    /** event_id integer */
    public var eventId: Int32?
    /** importance integer */
    public var importance: Int32?
    /** owner_id integer */
    public var ownerId: Int64?
    /** owner_name string */
    public var ownerName: String?
    /** owner_type string */
    public var ownerType: OwnerType?
    /** response string */
    public var response: String?
    /** text string */
    public var text: String?
    /** title string */
    public var title: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        nillableDictionary["event_id"] = self.eventId?.encodeToJSON()
        nillableDictionary["importance"] = self.importance?.encodeToJSON()
        nillableDictionary["owner_id"] = self.ownerId?.encodeToJSON()
        nillableDictionary["owner_name"] = self.ownerName
        nillableDictionary["owner_type"] = self.ownerType?.rawValue
        nillableDictionary["response"] = self.response
        nillableDictionary["text"] = self.text
        nillableDictionary["title"] = self.title
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
