//
// GetCharactersCharacterIdPlanetsPlanetIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdPlanetsPlanetIdOk: JSONEncodable {
    /** links array */
    public var links: [GetCharactersCharacterIdPlanetsPlanetIdOkLinks]?
    /** pins array */
    public var pins: [GetCharactersCharacterIdPlanetsPlanetIdOkPins]?
    /** routes array */
    public var routes: [GetCharactersCharacterIdPlanetsPlanetIdOkRoutes]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["links"] = self.links?.encodeToJSON()
        nillableDictionary["pins"] = self.pins?.encodeToJSON()
        nillableDictionary["routes"] = self.routes?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
