//
// GetCorporationsCorporationIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCorporationsCorporationIdOk: JSONEncodable {
    /** id of alliance that corporation is a member of, if any */
    public var allianceId: Int32?
    /** ceo_id integer */
    public var ceoId: Int32?
    /** the full name of the corporation */
    public var corporationName: String?
    /** member_count integer */
    public var memberCount: Int32?
    /** the short name of the corporation */
    public var ticker: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["alliance_id"] = self.allianceId?.encodeToJSON()
        nillableDictionary["ceo_id"] = self.ceoId?.encodeToJSON()
        nillableDictionary["corporation_name"] = self.corporationName
        nillableDictionary["member_count"] = self.memberCount?.encodeToJSON()
        nillableDictionary["ticker"] = self.ticker
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
