//
// GetCharactersCharacterIdCalendar200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** event */
public class GetCharactersCharacterIdCalendar200Ok: JSONEncodable {
    public enum EventResponse: String { 
        case Declined = "declined"
        case NotResponded = "not_responded"
        case Accepted = "accepted"
        case Tentative = "tentative"
    }
    /** event_date string */
    public var eventDate: NSDate?
    /** event_id integer */
    public var eventId: Int32?
    /** event_response string */
    public var eventResponse: EventResponse?
    /** importance integer */
    public var importance: Int32?
    /** title string */
    public var title: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["event_date"] = self.eventDate?.encodeToJSON()
        nillableDictionary["event_id"] = self.eventId?.encodeToJSON()
        nillableDictionary["event_response"] = self.eventResponse?.rawValue
        nillableDictionary["importance"] = self.importance?.encodeToJSON()
        nillableDictionary["title"] = self.title
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
