//
// GetCharactersCharacterIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdOk: JSONEncodable {
    public enum Gender: String { 
        case Female = "female"
        case Male = "male"
    }
    /** ancestry_id integer */
    public var ancestryId: Int32?
    /** Creation date of the character */
    public var birthday: NSDate?
    /** bloodline_id integer */
    public var bloodlineId: Int32?
    /** The character&#39;s corporation ID */
    public var corporationId: Int32?
    /** description string */
    public var description: String?
    /** gender string */
    public var gender: Gender?
    /** The name of the character */
    public var name: String?
    /** race_id integer */
    public var raceId: Int32?
    /** security_status number */
    public var securityStatus: Float?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["ancestry_id"] = self.ancestryId?.encodeToJSON()
        nillableDictionary["birthday"] = self.birthday?.encodeToJSON()
        nillableDictionary["bloodline_id"] = self.bloodlineId?.encodeToJSON()
        nillableDictionary["corporation_id"] = self.corporationId?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["gender"] = self.gender?.rawValue
        nillableDictionary["name"] = self.name
        nillableDictionary["race_id"] = self.raceId?.encodeToJSON()
        nillableDictionary["security_status"] = self.securityStatus
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
