//
// GetCharactersCharacterIdClonesOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdClonesOk: JSONEncodable {
    public var homeLocation: GetCharactersCharacterIdClonesOkHomeLocation?
    /** jump_clones array */
    public var jumpClones: [GetCharactersCharacterIdClonesOkJumpClones]?
    /** last_jump_date string */
    public var lastJumpDate: NSDate?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["home_location"] = self.homeLocation?.encodeToJSON()
        nillableDictionary["jump_clones"] = self.jumpClones?.encodeToJSON()
        nillableDictionary["last_jump_date"] = self.lastJumpDate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
