//
// GetCharactersCharacterIdSkillsOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetCharactersCharacterIdSkillsOk: JSONEncodable {
    /** skills array */
    public var skills: [GetCharactersCharacterIdSkillsOkSkills]?
    /** total_sp integer */
    public var totalSp: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["skills"] = self.skills?.encodeToJSON()
        nillableDictionary["total_sp"] = self.totalSp?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
