//
// GetFleetsFleetIdMembers200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetFleetsFleetIdMembers200Ok: JSONEncodable {
    public enum Role: String { 
        case FleetCommander = "fleet_commander"
        case WingCommander = "wing_commander"
        case SquadCommander = "squad_commander"
        case SquadMember = "squad_member"
    }
    /** character_id integer */
    public var characterId: Int32?
    /** join_time string */
    public var joinTime: NSDate?
    /** Member’s role in fleet */
    public var role: Role?
    /** Localized role names */
    public var roleName: String?
    /** ship_type_id integer */
    public var shipTypeId: Int32?
    /** Solar system the member is located in */
    public var solarSystemId: Int32?
    /** ID of the squad the member is in. If not applicable, will be set to -1 */
    public var squadId: Int64?
    /** Station in which the member is docked in, if applicable */
    public var stationId: Int64?
    /** Whether the member take fleet warps */
    public var takesFleetWarp: Bool?
    /** ID of the wing the member is in. If not applicable, will be set to -1 */
    public var wingId: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["character_id"] = self.characterId?.encodeToJSON()
        nillableDictionary["join_time"] = self.joinTime?.encodeToJSON()
        nillableDictionary["role"] = self.role?.rawValue
        nillableDictionary["role_name"] = self.roleName
        nillableDictionary["ship_type_id"] = self.shipTypeId?.encodeToJSON()
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["squad_id"] = self.squadId?.encodeToJSON()
        nillableDictionary["station_id"] = self.stationId?.encodeToJSON()
        nillableDictionary["takes_fleet_warp"] = self.takesFleetWarp
        nillableDictionary["wing_id"] = self.wingId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
