//
// GetFleetsFleetIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetFleetsFleetIdOk: JSONEncodable {
    /** Is free-move enabled */
    public var isFreeMove: Bool?
    /** Does the fleet have an active fleet advertisement */
    public var isRegistered: Bool?
    /** Is EVE Voice enabled */
    public var isVoiceEnabled: Bool?
    /** Fleet MOTD in CCP flavoured HTML */
    public var motd: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["is_free_move"] = self.isFreeMove
        nillableDictionary["is_registered"] = self.isRegistered
        nillableDictionary["is_voice_enabled"] = self.isVoiceEnabled
        nillableDictionary["motd"] = self.motd
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
