//
// GetFleetsFleetIdWings200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetFleetsFleetIdWings200Ok: JSONEncodable {
    /** id integer */
    public var id: Int64?
    /** name string */
    public var name: String?
    /** squads array */
    public var squads: [FleetsfleetIdwingsSquads]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["squads"] = self.squads?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
