//
// GetIncursions200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetIncursions200Ok: JSONEncodable {
    public enum State: String { 
        case Withdrawing = "withdrawing"
        case Mobilizing = "mobilizing"
        case Established = "established"
    }
    /** The constellation id in which this incursion takes place */
    public var constellationId: Int32?
    /** The attacking faction&#39;s id */
    public var factionId: Int32?
    /** Whether the final encounter has boss or not */
    public var hasBoss: Bool?
    /** A list of infested solar system ids that are a part of this incursion */
    public var infestedSolarSystems: [Int32]?
    /** Influence of this incursion as a float from 0 to 1 */
    public var influence: Float?
    /** Staging solar system for this incursion */
    public var stagingSolarSystemId: Int32?
    /** The state of this incursion */
    public var state: State?
    /** The type of this incursion */
    public var type: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["constellation_id"] = self.constellationId?.encodeToJSON()
        nillableDictionary["faction_id"] = self.factionId?.encodeToJSON()
        nillableDictionary["has_boss"] = self.hasBoss
        nillableDictionary["infested_solar_systems"] = self.infestedSolarSystems?.encodeToJSON()
        nillableDictionary["influence"] = self.influence
        nillableDictionary["staging_solar_system_id"] = self.stagingSolarSystemId?.encodeToJSON()
        nillableDictionary["state"] = self.state?.rawValue
        nillableDictionary["type"] = self.type
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
