//
// GetIndustryFacilities200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetIndustryFacilities200Ok: JSONEncodable {
    /** ID of the facility */
    public var facilityId: Int64?
    /** Owner of the facility */
    public var ownerId: Int32?
    /** Region ID where the facility is */
    public var regionId: Int32?
    /** Solar system ID where the facility is */
    public var solarSystemId: Int32?
    /** Tax imposed by the facility */
    public var tax: Float?
    /** Type ID of the facility */
    public var typeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["facility_id"] = self.facilityId?.encodeToJSON()
        nillableDictionary["owner_id"] = self.ownerId?.encodeToJSON()
        nillableDictionary["region_id"] = self.regionId?.encodeToJSON()
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["tax"] = self.tax
        nillableDictionary["type_id"] = self.typeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
