//
// GetInsurancePrices200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetInsurancePrices200Ok: JSONEncodable {
    /** A list of a available insurance levels for this ship type */
    public var levels: [InsurancepricesLevels]?
    /** type_id integer */
    public var typeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["levels"] = self.levels?.encodeToJSON()
        nillableDictionary["type_id"] = self.typeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
