//
// GetKillmailsKillmailIdKillmailHashOkVictimItems.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** item object */
public class GetKillmailsKillmailIdKillmailHashOkVictimItems: JSONEncodable {
    /** flag integer */
    public var flag: Int32?
    /** item_type_id integer */
    public var itemTypeId: Int32?
    /** quantity_destroyed integer */
    public var quantityDestroyed: Int64?
    /** quantity_dropped integer */
    public var quantityDropped: Int64?
    /** singleton integer */
    public var singleton: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["flag"] = self.flag?.encodeToJSON()
        nillableDictionary["item_type_id"] = self.itemTypeId?.encodeToJSON()
        nillableDictionary["quantity_destroyed"] = self.quantityDestroyed?.encodeToJSON()
        nillableDictionary["quantity_dropped"] = self.quantityDropped?.encodeToJSON()
        nillableDictionary["singleton"] = self.singleton?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
