//
// GetKillmailsKillmailIdKillmailHashOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetKillmailsKillmailIdKillmailHashOk: JSONEncodable {
    /** attackers array */
    public var attackers: [GetKillmailsKillmailIdKillmailHashOkAttackers]?
    /** ID of the killmail */
    public var killmailId: Int32?
    /** Time that the victim was killed and the killmail generated  */
    public var killmailTime: NSDate?
    /** Moon if the kill took place at one */
    public var moonId: Int32?
    /** Solar system that the kill took place in  */
    public var solarSystemId: Int32?
    public var victim: GetKillmailsKillmailIdKillmailHashOkVictim?
    /** War if the killmail is generated in relation to an official war  */
    public var warId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["attackers"] = self.attackers?.encodeToJSON()
        nillableDictionary["killmail_id"] = self.killmailId?.encodeToJSON()
        nillableDictionary["killmail_time"] = self.killmailTime?.encodeToJSON()
        nillableDictionary["moon_id"] = self.moonId?.encodeToJSON()
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["victim"] = self.victim?.encodeToJSON()
        nillableDictionary["war_id"] = self.warId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
