//
// GetKillmailsKillmailIdKillmailHashUnprocessableEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** killmail_id and/or killmail_hash is not valid */
public class GetKillmailsKillmailIdKillmailHashUnprocessableEntity: JSONEncodable {
    /** error message */
    public var error: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["error"] = self.error
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
