//
// GetKillmailsKillmailIdKillmailHashOkAttackers.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** attacker object */
public class GetKillmailsKillmailIdKillmailHashOkAttackers: JSONEncodable {
    /** alliance_id integer */
    public var allianceId: Int32?
    /** character_id integer */
    public var characterId: Int32?
    /** corporation_id integer */
    public var corporationId: Int32?
    /** damage_done integer */
    public var damageDone: Int32?
    /** faction_id integer */
    public var factionId: Int32?
    /** Was the attacker the one to achieve the final blow  */
    public var finalBlow: Bool?
    /** Security status for the attacker  */
    public var securityStatus: Float?
    /** What ship was the attacker flying  */
    public var shipTypeId: Int32?
    /** What weapon was used by the attacker for the kill  */
    public var weaponTypeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["alliance_id"] = self.allianceId?.encodeToJSON()
        nillableDictionary["character_id"] = self.characterId?.encodeToJSON()
        nillableDictionary["corporation_id"] = self.corporationId?.encodeToJSON()
        nillableDictionary["damage_done"] = self.damageDone?.encodeToJSON()
        nillableDictionary["faction_id"] = self.factionId?.encodeToJSON()
        nillableDictionary["final_blow"] = self.finalBlow
        nillableDictionary["security_status"] = self.securityStatus
        nillableDictionary["ship_type_id"] = self.shipTypeId?.encodeToJSON()
        nillableDictionary["weapon_type_id"] = self.weaponTypeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
