//
// GetKillmailsKillmailIdKillmailHashOkVictimItems1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** item object */
public class GetKillmailsKillmailIdKillmailHashOkVictimItems1: JSONEncodable {
    /** Flag for the location of the item  */
    public var flag: Int32?
    /** item_type_id integer */
    public var itemTypeId: Int32?
    /** items array */
    public var items: [GetKillmailsKillmailIdKillmailHashOkVictimItems]?
    /** How many of the item were destroyed if any  */
    public var quantityDestroyed: Int64?
    /** How many of the item were dropped if any  */
    public var quantityDropped: Int64?
    /** singleton integer */
    public var singleton: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["flag"] = self.flag?.encodeToJSON()
        nillableDictionary["item_type_id"] = self.itemTypeId?.encodeToJSON()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["quantity_destroyed"] = self.quantityDestroyed?.encodeToJSON()
        nillableDictionary["quantity_dropped"] = self.quantityDropped?.encodeToJSON()
        nillableDictionary["singleton"] = self.singleton?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
