//
// GetKillmailsKillmailIdKillmailHashOkVictim.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** victim object */
public class GetKillmailsKillmailIdKillmailHashOkVictim: JSONEncodable {
    /** alliance_id integer */
    public var allianceId: Int32?
    /** character_id integer */
    public var characterId: Int32?
    /** corporation_id integer */
    public var corporationId: Int32?
    /** How much total damage was taken by the victim  */
    public var damageTaken: Int32?
    /** faction_id integer */
    public var factionId: Int32?
    /** items array */
    public var items: [GetKillmailsKillmailIdKillmailHashOkVictimItems1]?
    public var position: GetKillmailsKillmailIdKillmailHashOkVictimPosition?
    /** The ship that the victim was piloting and was destroyed  */
    public var shipTypeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["alliance_id"] = self.allianceId?.encodeToJSON()
        nillableDictionary["character_id"] = self.characterId?.encodeToJSON()
        nillableDictionary["corporation_id"] = self.corporationId?.encodeToJSON()
        nillableDictionary["damage_taken"] = self.damageTaken?.encodeToJSON()
        nillableDictionary["faction_id"] = self.factionId?.encodeToJSON()
        nillableDictionary["items"] = self.items?.encodeToJSON()
        nillableDictionary["position"] = self.position?.encodeToJSON()
        nillableDictionary["ship_type_id"] = self.shipTypeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
