//
// GetMarketsPrices200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetMarketsPrices200Ok: JSONEncodable {
    /** adjusted_price number */
    public var adjustedPrice: Float?
    /** average_price number */
    public var averagePrice: Float?
    /** type_id integer */
    public var typeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["adjusted_price"] = self.adjustedPrice
        nillableDictionary["average_price"] = self.averagePrice
        nillableDictionary["type_id"] = self.typeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
