//
// GetMarketsRegionIdHistory200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetMarketsRegionIdHistory200Ok: JSONEncodable {
    /** average number */
    public var average: Float?
    /** The date of this historical statistic entry */
    public var date: NSDate?
    /** highest number */
    public var highest: Float?
    /** lowest number */
    public var lowest: Float?
    /** Total number of orders happened that day */
    public var orderCount: Int64?
    /** Total */
    public var volume: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["average"] = self.average
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["highest"] = self.highest
        nillableDictionary["lowest"] = self.lowest
        nillableDictionary["order_count"] = self.orderCount?.encodeToJSON()
        nillableDictionary["volume"] = self.volume?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
