//
// GetSovereigntyCampaigns200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetSovereigntyCampaigns200Ok: JSONEncodable {
    public enum EventType: String { 
        case TcuDefense = "tcu_defense"
        case IhubDefense = "ihub_defense"
        case StationDefense = "station_defense"
        case StationFreeport = "station_freeport"
    }
    /** Score for all attacking parties, only present in Defense Events.  */
    public var attackersScore: Float?
    /** Unique ID for this campaign. */
    public var campaignId: Int32?
    /** The constellation in which the campaign will take place.  */
    public var constellationId: Int32?
    /** Defending alliance, only present in Defense Events  */
    public var defenderId: Int32?
    /** Score for the defending alliance, only present in Defense Events.  */
    public var defenderScore: Float?
    /** Type of event this campaign is for. tcu_defense, ihub_defense and station_defense are referred to as \&quot;Defense Events\&quot;, station_freeport as \&quot;Freeport Events\&quot;.  */
    public var eventType: EventType?
    /** Alliance participating and their respective scores, only present in Freeport Events.  */
    public var participants: [SovereigntycampaignsParticipants]?
    /** The solar system the structure is located in.  */
    public var solarSystemId: Int32?
    /** Time the event is scheduled to start.  */
    public var startTime: NSDate?
    /** The structure item ID that is related to this campaign.  */
    public var structureId: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["attackers_score"] = self.attackersScore
        nillableDictionary["campaign_id"] = self.campaignId?.encodeToJSON()
        nillableDictionary["constellation_id"] = self.constellationId?.encodeToJSON()
        nillableDictionary["defender_id"] = self.defenderId?.encodeToJSON()
        nillableDictionary["defender_score"] = self.defenderScore
        nillableDictionary["event_type"] = self.eventType?.rawValue
        nillableDictionary["participants"] = self.participants?.encodeToJSON()
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["start_time"] = self.startTime?.encodeToJSON()
        nillableDictionary["structure_id"] = self.structureId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
