//
// GetUniverseTypesTypeIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetUniverseTypesTypeIdOk: JSONEncodable {
    /** category_id integer */
    public var categoryId: Int32?
    /** graphic_id integer */
    public var graphicId: Int32?
    /** group_id integer */
    public var groupId: Int32?
    /** icon_id integer */
    public var iconId: Int32?
    /** type_description string */
    public var typeDescription: String?
    /** type_name string */
    public var typeName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["category_id"] = self.categoryId?.encodeToJSON()
        nillableDictionary["graphic_id"] = self.graphicId?.encodeToJSON()
        nillableDictionary["group_id"] = self.groupId?.encodeToJSON()
        nillableDictionary["icon_id"] = self.iconId?.encodeToJSON()
        nillableDictionary["type_description"] = self.typeDescription
        nillableDictionary["type_name"] = self.typeName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
