//
// GetUniverseStationsStationIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetUniverseStationsStationIdOk: JSONEncodable {
    /** solar_system_id integer */
    public var solarSystemId: Int32?
    /** the full name of the station */
    public var stationName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["station_name"] = self.stationName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
