//
// GetUniverseSchematicsSchematicIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetUniverseSchematicsSchematicIdOk: JSONEncodable {
    /** Time in seconds to process a run */
    public var cycleTime: Int32?
    /** schematic_name string */
    public var schematicName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cycle_time"] = self.cycleTime?.encodeToJSON()
        nillableDictionary["schematic_name"] = self.schematicName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
