//
// GetUniverseStructuresStructureIdOkPosition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Coordinates of the structure in Cartesian space relative to the Sun, in metres.  */
public class GetUniverseStructuresStructureIdOkPosition: JSONEncodable {
    /** x number */
    public var x: Float?
    /** y number */
    public var y: Float?
    /** z number */
    public var z: Float?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["x"] = self.x
        nillableDictionary["y"] = self.y
        nillableDictionary["z"] = self.z
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
