//
// GetUniverseStructuresStructureIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class GetUniverseStructuresStructureIdOk: JSONEncodable {
    /** The full name of the structure */
    public var name: String?
    public var position: GetUniverseStructuresStructureIdOkPosition?
    /** solar_system_id integer */
    public var solarSystemId: Int32?
    /** type_id integer */
    public var typeId: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["name"] = self.name
        nillableDictionary["position"] = self.position?.encodeToJSON()
        nillableDictionary["solar_system_id"] = self.solarSystemId?.encodeToJSON()
        nillableDictionary["type_id"] = self.typeId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
