//
// GetWarsWarIdOkDefender.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id */
public class GetWarsWarIdOkDefender: JSONEncodable {
    /** Alliance ID if and only if the defender is an alliance */
    public var allianceId: Int32?
    /** Corporation ID if and only if the defender is a corporation */
    public var corporationId: Int32?
    /** ISK value of ships the defender has killed */
    public var iskDestroyed: Float?
    /** The number of ships the defender has killed */
    public var shipsKilled: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["alliance_id"] = self.allianceId?.encodeToJSON()
        nillableDictionary["corporation_id"] = self.corporationId?.encodeToJSON()
        nillableDictionary["isk_destroyed"] = self.iskDestroyed
        nillableDictionary["ships_killed"] = self.shipsKilled?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
