//
// IndustrysystemsCostIndices.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** cost_indice object */
public class IndustrysystemsCostIndices: JSONEncodable {
    public enum Activity: String { 
        case None = "none"
        case Manufacturing = "manufacturing"
        case ResearchingTechnology = "researching_technology"
        case ResearchingTimeEfficiency = "researching_time_efficiency"
        case ResearchingMaterialEfficiency = "researching_material_efficiency"
        case Copying = "copying"
        case Duplicating = "duplicating"
        case Invention = "invention"
        case ReverseEngineering = "reverse_engineering"
    }
    /** activity string */
    public var activity: Activity?
    /** cost_index number */
    public var costIndex: Float?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["activity"] = self.activity?.rawValue
        nillableDictionary["cost_index"] = self.costIndex
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
