//
// InsurancepricesLevels.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** level object */
public class InsurancepricesLevels: JSONEncodable {
    /** cost number */
    public var cost: Float?
    /** Localized insurance level */
    public var name: String?
    /** payout number */
    public var payout: Float?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["cost"] = self.cost
        nillableDictionary["name"] = self.name
        nillableDictionary["payout"] = self.payout
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
