//
// PostFleetsFleetIdWingsWingIdSquadsCreated.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 201 created object */
public class PostFleetsFleetIdWingsWingIdSquadsCreated: JSONEncodable {
    /** The squad_id of the newly created squad */
    public var squadId: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["squad_id"] = self.squadId?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
