//
// PostCharactersCharacterIdMailMail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** mail schema */
public class PostCharactersCharacterIdMailMail: JSONEncodable {
    /** approved_cost integer */
    public var approvedCost: Int64?
    /** body string */
    public var body: String?
    /** recipients array */
    public var recipients: [CharacterscharacterIdmailRecipients1]?
    /** subject string */
    public var subject: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["approved_cost"] = self.approvedCost?.encodeToJSON()
        nillableDictionary["body"] = self.body
        nillableDictionary["recipients"] = self.recipients?.encodeToJSON()
        nillableDictionary["subject"] = self.subject
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
