//
// PostUniverseNames200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */
public class PostUniverseNames200Ok: JSONEncodable {
    public enum Category: String { 
        case Alliance = "alliance"
        case Character = "character"
        case Constellation = "constellation"
        case Corporation = "corporation"
        case InventoryType = "inventory_type"
        case Region = "region"
        case SolarSystem = "solar_system"
        case Station = "station"
    }
    /** category string */
    public var category: Category?
    /** id integer */
    public var id: Int32?
    /** name string */
    public var name: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["category"] = self.category?.rawValue
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
