//
// PutCharactersCharacterIdCalendarEventIdResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** response schema */
public class PutCharactersCharacterIdCalendarEventIdResponse: JSONEncodable {
    public enum Response: String { 
        case Accepted = "accepted"
        case Declined = "declined"
        case Tentative = "tentative"
    }
    /** response string */
    public var response: Response?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["response"] = self.response?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
