//
// PutCharactersCharacterIdMailMailIdContents.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** contents object */
public class PutCharactersCharacterIdMailMailIdContents: JSONEncodable {
    /** Labels to assign to the mail. Pre-existing labels are unassigned. */
    public var labels: [Int64]?
    /** Whether the mail is flagged as read */
    public var read: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["labels"] = self.labels?.encodeToJSON()
        nillableDictionary["read"] = self.read
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
