//
// PutFleetsFleetIdNewSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** new_settings object */
public class PutFleetsFleetIdNewSettings: JSONEncodable {
    /** Should free-move be enabled in the fleet */
    public var isFreeMove: Bool?
    /** New fleet MOTD in CCP flavoured HTML */
    public var motd: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["is_free_move"] = self.isFreeMove
        nillableDictionary["motd"] = self.motd
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
